package com.jhopesoft.framework.dao.entity.dictionary;
// Generated 2016-11-2 20:01:19 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

/**
 * FDictionarygroup generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "f_dictionarygroup", uniqueConstraints = {
		@UniqueConstraint(columnNames = "groupcode"), @UniqueConstraint(columnNames = "groupname") })
@SuppressWarnings("serial")

public class FDictionarygroup implements java.io.Serializable {

	private String groupid;
	private String groupcode;
	private String groupname;
	private Boolean issystem;
	private String iconcls;
	private String remark;
	private Set<FDictionary> FDictionaries = new HashSet<FDictionary>(0);

	public FDictionarygroup() {
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "groupid", unique = true, nullable = false, length = 40)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "groupcode", unique = true, nullable = false, length = 20)
	public String getGroupcode() {
		return this.groupcode;
	}

	public void setGroupcode(String groupcode) {
		this.groupcode = groupcode;
	}

	@Column(name = "groupname", unique = true, nullable = false, length = 50)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "issystem")
	public Boolean getIssystem() {
		return this.issystem;
	}

	public void setIssystem(Boolean issystem) {
		this.issystem = issystem;
	}

	@Column(name = "iconcls", length = 50)
	public String getIconcls() {
		return this.iconcls;
	}

	public void setIconcls(String iconcls) {
		this.iconcls = iconcls;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FDictionarygroup")
	public Set<FDictionary> getFDictionaries() {
		return this.FDictionaries;
	}

	public void setFDictionaries(Set<FDictionary> FDictionaries) {
		this.FDictionaries = FDictionaries;
	}

}
