package com.jhopesoft.framework.dao.entity.dataobject;
// default package
// Generated 2018-3-24 20:17:12 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

/**
 * FDataobjectparentdefine generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@DynamicUpdate
@Table(name = "f_dataobjectparentdefine", uniqueConstraints = @UniqueConstraint(columnNames = {
		"objectid", "fieldahead" }))
@Cache(region = "beanCache", usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)

public class FDataobjectparentdefine implements java.io.Serializable {

	private String objectparentid;
	private FDataobject FDataobject;
	private String fieldahead;
	private String defaulttitle;
	private String title;
	private String remark;

	public FDataobjectparentdefine() {
	}

	public FDataobjectparentdefine(FDataobject FDataobject, String fieldahead,
			String defaulttitle, String title) {
		this.FDataobject = FDataobject;
		this.fieldahead = fieldahead;
		this.defaulttitle = defaulttitle;
		this.title = title;
	}

	@Id
  @GeneratedValue(generator = "generator")
  @GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Column(name = "objectparentid", unique = true, nullable = false, length = 40)
	public String getObjectparentid() {
		return this.objectparentid;
	}

	public void setObjectparentid(String objectparentid) {
		this.objectparentid = objectparentid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "objectid", nullable = false)
	public FDataobject getFDataobject() {
		return this.FDataobject;
	}

	public void setFDataobject(FDataobject FDataobject) {
		this.FDataobject = FDataobject;
	}

	@Column(name = "fieldahead", nullable = false, length = 200)
	public String getFieldahead() {
		return this.fieldahead;
	}

	public void setFieldahead(String fieldahead) {
		this.fieldahead = fieldahead;
	}

	@Column(name = "defaulttitle", nullable = false, length = 200)
	public String getDefaulttitle() {
		return this.defaulttitle;
	}

	public void setDefaulttitle(String defaulttitle) {
		this.defaulttitle = defaulttitle;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
