package com.jhopesoft.framework.dao.entity.workflow;
// default package
// Generated 2017-9-7 14:43:54 by Hibernate Tools 5.2.0.Beta1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VActFinishTaskId generated by hbm2java
 */
@Embeddable
@SuppressWarnings("serial")

public class VActFinishTask implements java.io.Serializable {


  private String objectid;
  private String objectname;
  private String objecttitle;
  private String actBusinessKey;
  private String actBusinessName;
  private String title;
  private String actProcInstId;
  private String actProcDefId;
  private Date actStartTime;
  private Date actEndTime;
  private String actStartUserId;
  private String actEndActName;
  private String actCompleteTaskInfo;
  private Long actProcInstState;
  private String actProcState;
  private String actTaskDefKey;
  private String actExecuteTaskId;
  private String actExecuteTaskName;
  private String actAssigneeId;
  private Date actTaskStartTime;
  private Date actTaskEndTime;
  private String actTaskType;
  private String actTaskMessage;

  public VActFinishTask() {}


  public VActFinishTask(String actExecuteTaskId, Date actTaskStartTime) {
    this.actExecuteTaskId = actExecuteTaskId;
    this.actTaskStartTime = actTaskStartTime;
  }

  public VActFinishTask(String objectid, String objectname, String objecttitle, String actBusinessKey,
      String actBusinessName, String title, String actProcInstId, String actProcDefId, Date actStartTime,
      Date actEndTime, String actStartUserId, String actEndActName, String actCompleteTaskInfo, Long actProcInstState,
      String actProcState, String actTaskDefKey, String actExecuteTaskId, String actExecuteTaskName,
      String actAssigneeId, Date actTaskStartTime, Date actTaskEndTime, String actTaskType, String actTaskMessage) {
    this.objectid = objectid;
    this.objectname = objectname;
    this.objecttitle = objecttitle;
    this.actBusinessKey = actBusinessKey;
    this.actBusinessName = actBusinessName;
    this.title = title;
    this.actProcInstId = actProcInstId;
    this.actProcDefId = actProcDefId;
    this.actStartTime = actStartTime;
    this.actEndTime = actEndTime;
    this.actStartUserId = actStartUserId;
    this.actEndActName = actEndActName;
    this.actCompleteTaskInfo = actCompleteTaskInfo;
    this.actProcInstState = actProcInstState;
    this.actProcState = actProcState;
    this.actTaskDefKey = actTaskDefKey;
    this.actExecuteTaskId = actExecuteTaskId;
    this.actExecuteTaskName = actExecuteTaskName;
    this.actAssigneeId = actAssigneeId;
    this.actTaskStartTime = actTaskStartTime;
    this.actTaskEndTime = actTaskEndTime;
    this.actTaskType = actTaskType;
    this.actTaskMessage = actTaskMessage;
  }



  @Column(name = "objectid", length = 40)
  public String getObjectid() {
    return this.objectid;
  }

  public void setObjectid(String objectid) {
    this.objectid = objectid;
  }


  @Column(name = "objectname", length = 50)
  public String getObjectname() {
    return this.objectname;
  }

  public void setObjectname(String objectname) {
    this.objectname = objectname;
  }


  @Column(name = "objecttitle", length = 100)
  public String getObjecttitle() {
    return this.objecttitle;
  }

  public void setObjecttitle(String objecttitle) {
    this.objecttitle = objecttitle;
  }


  @Column(name = "act_Business_Key")
  public String getActBusinessKey() {
    return this.actBusinessKey;
  }

  public void setActBusinessKey(String actBusinessKey) {
    this.actBusinessKey = actBusinessKey;
  }


  @Column(name = "act_Business_Name", length = 65535)
  public String getActBusinessName() {
    return this.actBusinessName;
  }

  public void setActBusinessName(String actBusinessName) {
    this.actBusinessName = actBusinessName;
  }


  @Column(name = "title", length = 65535)
  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Column(name = "act_Proc_Inst_Id", length = 64)
  public String getActProcInstId() {
    return this.actProcInstId;
  }

  public void setActProcInstId(String actProcInstId) {
    this.actProcInstId = actProcInstId;
  }


  @Column(name = "act_Proc_Def_Id", length = 64)
  public String getActProcDefId() {
    return this.actProcDefId;
  }

  public void setActProcDefId(String actProcDefId) {
    this.actProcDefId = actProcDefId;
  }


  @Column(name = "act_Start_Time", length = 19)
  public Date getActStartTime() {
    return this.actStartTime;
  }

  public void setActStartTime(Date actStartTime) {
    this.actStartTime = actStartTime;
  }


  @Column(name = "act_End_Time", length = 19)
  public Date getActEndTime() {
    return this.actEndTime;
  }

  public void setActEndTime(Date actEndTime) {
    this.actEndTime = actEndTime;
  }


  @Column(name = "act_Start_User_Id")
  public String getActStartUserId() {
    return this.actStartUserId;
  }

  public void setActStartUserId(String actStartUserId) {
    this.actStartUserId = actStartUserId;
  }


  @Column(name = "act_End_Act_Name")
  public String getActEndActName() {
    return this.actEndActName;
  }

  public void setActEndActName(String actEndActName) {
    this.actEndActName = actEndActName;
  }


  @Column(name = "act_Complete_Task_Info", length = 341)
  public String getActCompleteTaskInfo() {
    return this.actCompleteTaskInfo;
  }

  public void setActCompleteTaskInfo(String actCompleteTaskInfo) {
    this.actCompleteTaskInfo = actCompleteTaskInfo;
  }


  @Column(name = "act_Proc_Inst_State")
  public Long getActProcInstState() {
    return this.actProcInstState;
  }

  public void setActProcInstState(Long actProcInstState) {
    this.actProcInstState = actProcInstState;
  }


  @Column(name = "act_Proc_State", length = 260)
  public String getActProcState() {
    return this.actProcState;
  }

  public void setActProcState(String actProcState) {
    this.actProcState = actProcState;
  }


  @Column(name = "act_Task_Def_Key")
  public String getActTaskDefKey() {
    return this.actTaskDefKey;
  }

  public void setActTaskDefKey(String actTaskDefKey) {
    this.actTaskDefKey = actTaskDefKey;
  }


  @Column(name = "act_Execute_Task_Id", nullable = false, length = 64)
  public String getActExecuteTaskId() {
    return this.actExecuteTaskId;
  }

  public void setActExecuteTaskId(String actExecuteTaskId) {
    this.actExecuteTaskId = actExecuteTaskId;
  }


  @Column(name = "act_Execute_Task_Name")
  public String getActExecuteTaskName() {
    return this.actExecuteTaskName;
  }

  public void setActExecuteTaskName(String actExecuteTaskName) {
    this.actExecuteTaskName = actExecuteTaskName;
  }


  @Column(name = "act_Assignee_Id")
  public String getActAssigneeId() {
    return this.actAssigneeId;
  }

  public void setActAssigneeId(String actAssigneeId) {
    this.actAssigneeId = actAssigneeId;
  }


  @Column(name = "act_Task_Start_Time", nullable = false, length = 19)
  public Date getActTaskStartTime() {
    return this.actTaskStartTime;
  }

  public void setActTaskStartTime(Date actTaskStartTime) {
    this.actTaskStartTime = actTaskStartTime;
  }


  @Column(name = "act_Task_END_Time", length = 19)
  public Date getActTaskEndTime() {
    return this.actTaskEndTime;
  }

  public void setActTaskEndTime(Date actTaskEndTime) {
    this.actTaskEndTime = actTaskEndTime;
  }


  @Column(name = "act_Task_Type")
  public String getActTaskType() {
    return this.actTaskType;
  }

  public void setActTaskType(String actTaskType) {
    this.actTaskType = actTaskType;
  }


  @Column(name = "act_Task_Message", length = 4000)
  public String getActTaskMessage() {
    return this.actTaskMessage;
  }

  public void setActTaskMessage(String actTaskMessage) {
    this.actTaskMessage = actTaskMessage;
  }

}


