package com.jhopesoft.framework.dao.entity.utils;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import com.jhopesoft.framework.critical.Local;
import com.jhopesoft.framework.dao.entity.dataobject.FDataobject;
import com.jhopesoft.framework.dao.entity.dataobject.FDataobjectconditiondetail;
import com.jhopesoft.framework.dao.entity.dictionary.FNumbergroup;
import com.jhopesoft.framework.dao.entity.viewsetting.FovGridnavigateschemedetail;

/**
 * FFunction generated by hbm2java
 */
@Entity
@DynamicUpdate
@Table(name = "f_function", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
public class FFunction implements java.io.Serializable {

	private static final long serialVersionUID = -8653468231440451819L;
	private String functionid;
	private FNumbergroup FNumbergroup;
	private String groupname;
	private Integer orderno;
	private String title;
	private String expression;
	private String mysqlexpression;
	private String sqlserverexpression;
	private String oracleexpression;
	private Integer paramcount;
	private String paramtype;
	private String returntype;
	private String remark;
	private Set<FDataobjectconditiondetail> FDataobjectconditiondetails = new HashSet<FDataobjectconditiondetail>(0);
	private Set<FovGridnavigateschemedetail> fovGridnavigateschemedetails = new HashSet<FovGridnavigateschemedetail>(0);

	public FFunction(String functionid) {
		this.functionid = functionid;
	}

	public FFunction() {
		this.expression = " ";
	}

	public FFunction(String functionid, String groupname, Integer orderno, String title, String expression,
			String returntype) {
		this.functionid = functionid;
		this.groupname = groupname;
		this.orderno = orderno;
		this.title = title;
		this.expression = expression;
		this.returntype = returntype;
	}

	public FFunction(FNumbergroup fNumbergroup, String groupname, Integer orderno, String title, String paramtype,
			String returntype) {
		super();
		FNumbergroup = fNumbergroup;
		this.groupname = groupname;
		this.orderno = orderno;
		this.title = title;
		this.paramtype = paramtype;
		this.returntype = returntype;
		this.expression = " ";
	}

	@Transient
	public boolean isDateParamType() {
		return this.paramtype.equalsIgnoreCase("date") || this.paramtype.equalsIgnoreCase("datetime")
				|| this.paramtype.equalsIgnoreCase("timestramp");
	}

	@Transient
	public boolean isNumberParamType() {
		return this.paramtype.equalsIgnoreCase("number") || this.paramtype.equalsIgnoreCase("double")
				|| this.paramtype.equalsIgnoreCase("float") || this.paramtype.equalsIgnoreCase("integer")
				|| this.paramtype.equalsIgnoreCase("money");
	}

	@Transient
	public boolean isPercentType() {
		return this.paramtype.equalsIgnoreCase("percent");
	}

	@Id
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Column(name = "functionid", unique = true, nullable = false, length = 40)
	public String getFunctionid() {
		return this.functionid;
	}

	public void setFunctionid(String functionid) {
		this.functionid = functionid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numbergroupid")
	public FNumbergroup getFNumbergroup() {
		return this.FNumbergroup;
	}

	public void setFNumbergroup(FNumbergroup FNumbergroup) {
		this.FNumbergroup = FNumbergroup;
	}

	@Column(name = "groupname", nullable = false, length = 50)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "orderno", nullable = false)
	public Integer getOrderno() {
		return this.orderno;
	}

	public void setOrderno(Integer orderno) {
		this.orderno = orderno;
	}

	@Column(name = "title", unique = true, nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "expression", nullable = false, length = 200)
	public String getExpression() {
		return this.expression;
	}

	@Transient
	public String getSqlExpression(FDataobject dataobject) {
		if (getFNumbergroup() != null)
			return getFNumbergroup().genFunctionExpression();
		if (Local.getBusinessDao().isMysql())
			return getMysqlexpression();
		else if (Local.getBusinessDao().isOracle())
			return getOracleexpression();
		else if (Local.getBusinessDao().isSqlserver())
			return getSqlserverexpression();
		else
			return null;
	}

	public void setExpression(String expression) {
		if (expression != null)
			this.expression = expression;
	}

	@Column(name = "mysqlexpression", length = 2000)
	public String getMysqlexpression() {
		return this.mysqlexpression;
	}

	public void setMysqlexpression(String mysqlexpression) {
		this.mysqlexpression = mysqlexpression;
	}

	@Column(name = "sqlserverexpression", length = 2000)
	public String getSqlserverexpression() {
		return this.sqlserverexpression;
	}

	public void setSqlserverexpression(String sqlserverexpression) {
		this.sqlserverexpression = sqlserverexpression;
	}

	@Column(name = "oracleexpression", length = 2000)
	public String getOracleexpression() {
		return this.oracleexpression;
	}

	public void setOracleexpression(String oracleexpression) {
		this.oracleexpression = oracleexpression;
	}

	@Column(name = "paramcount")
	public Integer getParamcount() {
		return this.paramcount;
	}

	public void setParamcount(Integer paramcount) {
		this.paramcount = paramcount;
	}

	@Column(name = "returntype", nullable = false, length = 200)
	public String getReturntype() {
		return this.returntype;
	}

	public void setReturntype(String returntype) {
		this.returntype = returntype;
	}

	@Column(name = "paramtype", nullable = false, length = 200)
	public String getParamtype() {
		return paramtype;
	}

	public void setParamtype(String paramtype) {
		this.paramtype = paramtype;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FFunction")
	public Set<FDataobjectconditiondetail> getFDataobjectconditiondetails() {
		return this.FDataobjectconditiondetails;
	}

	public void setFDataobjectconditiondetails(Set<FDataobjectconditiondetail> FDataobjectconditiondetails) {
		this.FDataobjectconditiondetails = FDataobjectconditiondetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FFunction")
	public Set<FovGridnavigateschemedetail> getFovGridnavigateschemedetails() {
		return this.fovGridnavigateschemedetails;
	}

	public void setFovGridnavigateschemedetails(Set<FovGridnavigateschemedetail> fovGridnavigateschemedetails) {
		this.fovGridnavigateschemedetails = fovGridnavigateschemedetails;
	}

}
