package com.jhopesoft.business.sales.entity;
// default package

// Generated 2018-2-4 20:27:48 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SlCity generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sl_city", uniqueConstraints = @UniqueConstraint(columnNames = { "province_id_", "name_" }))
public class SlCity implements java.io.Serializable {

	private String id;
	private SlProvince slProvince;
	private String name;
	private String postCode;
	private String remark;

	public SlCity() {
	}

	public SlCity(String id, SlProvince slProvince, String name) {
		this.id = id;
		this.slProvince = slProvince;
		this.name = name;
	}

	public SlCity(String id, SlProvince slProvince, String name, String postCode, String remark) {
		this.id = id;
		this.slProvince = slProvince;
		this.name = name;
		this.postCode = postCode;
		this.remark = remark;
	}

	@Id

	@Column(name = "id_", unique = true, nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "province_id_", nullable = false)
	public SlProvince getSlProvince() {
		return this.slProvince;
	}

	public void setSlProvince(SlProvince slProvince) {
		this.slProvince = slProvince;
	}

	@Column(name = "name_", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "post_code", length = 10)
	public String getPostCode() {
		return this.postCode;
	}

	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	@Column(name = "remark_", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
